# Programming fundamental concepts: Modules and Numpy

*This assignment is not obligatory*


## Introduction

In the last tutorial we have covered the basics of Python programming, including variables, data types, and control structures. We also introduced some fundamental programming concepts such as loops and conditionals. In this tutorial we will take a closer look at functions and how to use them effectively in your code. We will not only use built-in functions but also import them from external libraries.

Throughout this tutorial, we will also focus on file handling in Python, including reading from and writing to files. This is an essential skill, since we will be working a lot with data stored in files.



### Useful tools

During coding, you will often need to look up how certain functions work. There are several useful tools to help you with this:
- The [Python documentation](https://docs.python.org/3/) or library documentation such as [NumPy](https://numpy.org/doc/stable/) and [Pandas](https://pandas.pydata.org/pandas-docs/stable/) are great resources.
- AI tools like [ChatGPT](https://chat.openai.com/) and [Copilot](https://github.com/features/copilot).
- Online forums and communities such as [Stack Overflow](https://stackoverflow.com/).


## Python packages

for this assignment we will be using the following packages:
- `numpy`: for numerical operations
- `pandas`: for data manipulation and analysis
- `os`: for interacting with the operating system

These should be installed in your Python environment. If you haven't installed them yet, you can do so using conda:

```bash
conda install numpy
```


> **Task 1:**
>
> Let's start by importing the necessary libraries.
>
> ```python
> import numpy as np
> import pandas as pd
> import os
> ```

In [2]:
import numpy as np 
import pandas as pd 
import os # operating system library 

### Numpy
Numpy (numpy documentation: https://numpy.org/doc/stable/) is one of the most popular libraries for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. Numpy is particularly useful for handling large datasets and performing complex mathematical operations efficiently. You will be using this library extensively throughout MUDE.

We will start by creating a simple array using Numpy after which we will focus on indexing and slicing. Indexing and slicing works similarly to Python lists, but with some additional features. 

A list of useful numpy functions:

- np.array(): Create an array
- np.arange(): Create an array with a range of values
- np.zeros(): Create an array filled with zeros
- np.ones(): Create an array filled with ones
- np.eye(): Create an identity matrix
- np.reshape(): Reshape an array
- np.transpose(): Transpose an array
- np.concatenate(): Concatenate arrays
- np.split(): Split an array
- np.mean(): Compute the mean of an array
- np.sum(): Compute the sum of an array
- np.max(): Find the maximum value in an array
- np.min(): Find the minimum value in an array
- np.std(): Compute the standard deviation of an array
- np.dot(): Compute the dot product of two arrays
- np.cross(): Compute the cross product of two arrays
- np.linalg.inv(): Compute the inverse of a matrix
- np.linalg.det(): Compute the determinant of a matrix
- np.random.rand(): Generate random numbers
- np.random.randn(): Generate random numbers from a standard normal distribution


In [3]:
# Create a 1D array
# help(np.array)
oned_array = np.array([0, 2, 4, 6, 8, 10]) 
print(oned_array)

# Create a 2D array
twod_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(twod_array)

# Append a new row to the 2D array
# help(np.append)
new_row = np.array([11, 12, 13, 14, 15]) 
new_twod_array = np.append(twod_array, [new_row], axis=0)
print(new_twod_array)


[ 0  2  4  6  8 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


> **Task 2:**
>
> We will now create a np.array with 10 rows and 3 columns. The first column is filled from 1 to 10, the second column is filled with the squares of the first column, and the third column is filled with the cubes of the first column. After we have created the array we will save it to a file.
>
> I will show you two ways to do this:
> - Starting with an empty array and filling it in a loop.
> - creating 3 separate arrays for each column and then combining them.

In [14]:
# Method 1: Starting with an empty array and filling it in a loop 
array = np.empty((10, 3), dtype = int) # creating an empty array 

for i in range(10):
    n = i + 1 
    array[i, 0] = n 
    array[i, 1] = n ** 2 
    array[i, 2] = n ** 3 

# Method 2: Creating 3 separate arrays for each column and then combining them 
arr1 = np.arange(1, 11) 
arr2 = arr1 ** 2 
arr3 = arr1 ** 3 

arr = np.column_stack((arr1, arr2, arr3))

# Lets check
print(array)
print(arr)

# save the file as csv
np.savetxt('array.csv', (array), delimiter=',')
np.savetxt('arr.csv', (arr), delimiter=',')


[[   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]]
[[   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]]


> **Task 3:**
>
> Now we will use some of numpy's powerful features to manipulate our data. Let's try some matrix operations. First, we will create a 3x3 matrix and perform some basic operations on it.

In [28]:
# Perform basic operations
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("This is the matrix M:") 
print(M)

b = np.array([3, 6, 9])
print("This is the vector b:", b)

# Matrix multiplication
multiply = np.matmul(M, b, out=None)
print("This is matrix M multiplied by vectorn b:")
print(multiply)

# Compute the inverse and determinant 
inverse = np.linalg.inv(M)
print("This is the inverse of the matrix M:")
print(inverse)

determinant = np.linalg.det(M)
print("The determinant of matrix M  is equal to", determinant, ".")



This is the matrix M:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
This is the vector b: [3 6 9]
This is matrix M multiplied by vectorn b:
[ 42  96 150]
This is the inverse of the matrix M:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
The determinant of matrix M  is equal to -9.51619735392994e-16 .


## os
Now that we have our data saved in a CSV file, we can use the `os` module to interact with the file system. For example, we can check if the file exists, remove it, or rename it.

some useful os functions:
- `os.path.exists(path)`: Check if a file or directory exists
- `os.remove(path)`: Remove a file
- `os.rename(old, new)`: Rename a file or directory
- `os.listdir(path)`: List all files and directories in a directory
- `os.getcwd()`: Get the current working directory
- `os.chdir(path)`: Change the current working directory
- `os.mkdir(path)`: Create a new directory
- `os.makedirs(path)`: Create a new directory and all intermediate directories
- `os.path.join(path, *paths)`: Join one or more path components intelligently


In [ ]:
# List all files in the current directory
os.listdir()

# Get the current working directory
os.getcwd()


'c:\\Users\\tmest\\MUDE\\Week_3\\PA1.3'

## Pandas

Now we will use pandas to import our newly created CSV file and perform some data analysis. We could also do this with other libraries, such as numpy, but pandas is specifically designed for data manipulation and analysis.

Some useful pandas functions include:

- `pd.read_csv()`: Read a CSV file into a DataFrame.
- `df.head()`: Display the first few rows of a DataFrame.
- `df.describe()`: Generate descriptive statistics.



> **Task 4:**
>
> Import our my_array.csv file using pandas and display the first few rows as well as the summary statistics.

In [44]:
# Import our my_array.csv file using pandas
array_csv = pd.read_csv("array.csv")
arr_csv = pd.read_csv("arr.csv")

# Display the first few rows
df.head()

# Display the summary statistics
df.describe() 

# Transform the data
df_transformed = df.dropna()

# Create numpy array from DataFrame
arr_df = df_transformed.to_numpy()



> By Berend Bouvy, Delft University of Technology. CC BY 4.0, more info [on the Credits page of Workbook](https://mude.citg.tudelft.nl/workbook-2025/credits.html).